#!/usr/bin/env bash
# Docker wrapper script for python-github-webhook
# We expect /etc/id_github_deploy to be mounted in or otherwise present
# Needs libuid-wrapper to allow git clones over ssh to work when we're an arbitrary user

export HOME=/var/tmp/user
mkdir -p $HOME
chmod 700 $HOME
mkdir -p "$HOME"/.ssh
chmod 700 "$HOME"/.ssh
cp /etc/id_github_deploy "$HOME"/.ssh
chmod 600 "$HOME"/.ssh/id_github_deploy
git config --global core.sshCommand 'ssh -o StrictHostKeyChecking=no -i '"$HOME"/.ssh/id_github_deploy
export LD_PRELOAD=libuid_wrapper.so UID_WRAPPER=1 UID_WRAPPER_ROOT=1
/app/main.py
